package com.bendb.aoc.year2025

import kotlin.test.Test
import kotlin.test.assertEquals

class Day07Test {
    val sampleInput: String
      get() = """
            |.......S.......
            |...............
            |.......^.......
            |...............
            |......^.^......
            |...............
            |.....^.^.^.....
            |...............
            |....^.^...^....
            |...............
            |...^.^...^.^...
            |...............
            |..^...^.....^..
            |...............
            |.^.^.^.^.^...^.
            |...............
        """.trimMargin()

    val testInput: String
      get() = javaClass.classLoader.getResource("day07/input.txt")!!.readText()

    @Test
    fun testPartOne() {
        assertEquals(1662L, Day07.partOne(testInput))
    }

    @Test
    fun testPartTwo() {
        assertEquals(40941112789504L, Day07.partTwo(testInput))
    }
}
